[project]
name = "energy-system-modelling"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "ipykernel>=7.1.0",
    "loguru>=0.7.3",
    "matplotlib>=3.10.7",
    "numpy>=2.3.5",
    "pandas>=2.3.3",
    "pypsa>=1.0.4",
    "pytest>=9.0.1",
    "ruff>=0.14.6",
    "tqdm>=4.67.1",
]

[tool.ruff]
# Max line length (adjust as needed)
line-length = 100

# Treat all violations as errors (non-zero exit code)
fix = false

[tool.ruff.lint]
# Enable all default rules (recommended)
select = ["E", "F", "W"]  # E/W = pycodestyle, F = pyflakes
